# Copyright (c) 2026 Paulo Henrik Carvalho de Araújo
# Nexus AI Pro - High-Speed Tactical Audio Translation Dictionary
# Token-efficient modularization (< 500 lines)

import re

def fast_tactical_translator(txt_en):
    clean = txt_en.strip()
    c_lower = re.sub(r'[\!\?\.\,]', '', clean.lower()).strip()

    clock_map = {
        "1": "uma hora", "one": "uma hora",
        "2": "duas horas", "two": "duas horas",
        "3": "três horas", "three": "três horas",
        "4": "quatro horas", "four": "quatro horas",
        "5": "cinco horas", "five": "cinco horas",
        "6": "seis horas", "six": "seis horas",
        "7": "sete horas", "seven": "sete horas",
        "8": "oito horas", "eight": "oito horas",
        "9": "nove horas", "nine": "nove horas",
        "10": "dez horas", "ten": "dez horas",
        "11": "onze horas", "eleven": "onze horas",
        "12": "doze horas", "twelve": "doze horas"
    }

    m_clock = re.search(r'contact(?:\s+at)?\s+(1[0-2]|[1-9]|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)(?:\s+o\'?clock)?', c_lower)
    if m_clock:
        num = m_clock.group(1)
        pt_time = clock_map.get(num, num)
        return f"Contato às {pt_time}!", "URGENTE"

    cardinal_map = {
        "north": "ao Norte", "south": "ao Sul", "east": "a Leste", "west": "a Oeste",
        "northeast": "a Nordeste", "northwest": "a Noroeste", "southeast": "a Sudeste", "southwest": "a Sudoeste"
    }

    for en_dir, pt_dir in cardinal_map.items():
        if c_lower in [f"contact {en_dir}", f"contact to the {en_dir}", f"contact to {en_dir}", f"enemies to the {en_dir}", f"tigers to the {en_dir}", f"contact {en_dir}"]:
            return f"Contato {pt_dir}!", "URGENTE"
        if c_lower == en_dir:
            return f"{pt_dir.replace('a ', '').replace('ao ', '').capitalize()}!", "URGENTE"

    floor_map = {
        "first floor": "no primeiro andar",
        "1st floor": "no primeiro andar",
        "second floor": "no segundo andar",
        "2nd floor": "no segundo andar",
        "third floor": "no terceiro andar",
        "3rd floor": "no terceiro andar",
        "ground floor": "no térreo",
        "roof": "no telhado",
        "rooftop": "no telhado",
        "balcony": "na varanda",
        "window": "na janela",
        "doorway": "na porta"
    }

    for fl_en, fl_pt in floor_map.items():
        if fl_en in c_lower:
            if "contact" in c_lower:
                return f"Contato {fl_pt}!", "URGENTE"
            elif "movement" in c_lower or "moving" in c_lower:
                return f"Movimento {fl_pt}!", "URGENTE"
            elif "roger" in c_lower or "copy" in c_lower:
                return f"Ciente, {fl_pt}!", "NORMAL"

    ack_dict = {
        "roger that": ("Copiado!", "NORMAL"),
        "copy that": ("Copiado!", "NORMAL"),
        "roger": ("Copiado!", "NORMAL"),
        "copy": ("Copiado!", "NORMAL"),
        "affirmative": ("Afirmativo!", "NORMAL"),
        "negative": ("Negativo!", "NORMAL"),
        "on it": ("Em andamento!", "URGENTE"),
        "got it": ("Copiado!", "NORMAL")
    }
    if c_lower in ack_dict:
        pt_t, emo = ack_dict[c_lower]
        return pt_t, emo

    tactical_dict = {
        "противник, два часа дня!": ("Inimigo, 2 horas!", "URGENTE"),
        "пехота, 12 часов!": ("Infanteria, 12 horas!", "URGENTE"),
        "цель слева!": ("Alvo à esquerda!", "URGENTE"),
        "атакуют слева!": ("Atacam pela esquerda!", "URGENTE"),
        "цель 7 часов!": ("Alvo 7 horas!", "URGENTE"),
        "обходят нас с тыла!": ("Eles nos flanqueiam pela retaguarda!", "URGENTE"),
        "противник с тыла!": ("Inimigo pela retaguarda!", "URGENTE"),
        "противник справа!": ("Inimigo à direita!", "URGENTE"),
        "противник, час дня!": ("Inimigo 1 hora!", "URGENTE"),
        "впереди враг!": ("Inimigo à frente!", "URGENTE"),
        "противник 10 часов!": ("Inimigo 10 horas!", "URGENTE"),
        "замечен противник на юго-западе!": ("Inimigo avistado ao Sudoeste!", "URGENTE"),
        "противник северо-запад!": ("Inimigo Noroeste!", "URGENTE"),
        "подходит с востока!": ("Aproxima-se pelo Leste!", "URGENTE"),
        "вижу противника на два часа!": ("Vejo inimigo às 2 horas!", "URGENTE"),
        "вражеская пехота на 12 часов!": ("Infanteria inimiga às 12 horas!", "URGENTE"),
        "они атакуют слева!": ("Eles atacam pela esquerda!", "URGENTE"),
        "враг сзади!": ("Inimigo atrás!", "URGENTE"),
        "справа! справа!": ("À direita! À direita!", "URGENTE"),
        "вижу противника справа!": ("Vejo inimigo à direita!", "URGENTE"),
        "противник на один час!": ("Inimigo a 1 hora!", "URGENTE"),
        "впереди солдаты противника!": ("Soldados inimigos à frente!", "URGENTE"),
        "впереди враг! огонь!": ("Inimigo à frente! Fogo!", "URGENTE"),
        "вижу противника на 10 часов!": ("Vejo inimigo às 10 horas!", "URGENTE"),
        "вражеская цель на западе!": ("Alvo inimigo ao Oeste!", "URGENTE"),
        "они атакуют с юго-востока!": ("Eles estão atacando pelo Sudeste!", "URGENTE"),
        "противник на юге!": ("Inimigo ao Sul!", "URGENTE"),
        "противник! северо-запад!": ("Inimigo! Noroeste!", "URGENTE"),
        "противник на северо-востоке!": ("Inimigo ao Nordeste!", "URGENTE"),
        "цель на севере!": ("Alvo ao Norte!", "URGENTE"),
        "ходят с востока!": ("Eles vêm do Leste!", "URGENTE"),
        "first floor, roger that!": ("Primeiro andar, copiado!", "URGENTE"),
        "contact 7 o'clock!": ("Contato 7 horas!", "URGENTE"),
        "contact 6 o'clock!": ("Contato 6 horas!", "URGENTE"),
        "showtime, 12 o'clock!": ("Hora do show, 12 horas!", "URGENTE"),
        "contact, you're 11 o'clock!": ("Contato, às 11 horas!", "URGENTE"),
        "conte to the north east!": ("Contato ao Nordeste!", "URGENTE"),
        "hey! check your fire!": ("Ei! Cuidado com os tiros!", "URGENTE"),
        "contact at five o'clock!": ("Contato às 5 horas!", "URGENTE"),
        "4 o'clock!": ("4 horas!", "URGENTE"),
        "contact, three o'clock!": ("Contato, 3 horas!", "URGENTE"),
        "contact at two o'clock!": ("Contato às 2 horas!", "URGENTE"),
        "contact! 11 o'clock!": ("Contato! 11 horas!", "URGENTE"),
        "10 o'clock!": ("10 horas!", "URGENTE"),
        "contact west!": ("Contato a Oeste!", "URGENTE"),
        "contact to the southwest!": ("Contato ao Sudoeste!", "URGENTE"),
        "contact south east!": ("Contato ao Sudeste!", "URGENTE"),
        "contact south!": ("Contato ao Sul!", "URGENTE"),
        "contact northwest!": ("Contato ao Noroeste!", "URGENTE"),
        "contact to the north east!": ("Contato ao Nordeste!", "URGENTE"),
        "contact north!": ("Contato ao Norte!", "URGENTE"),
        "contact east!": ("Contato a Leste!", "URGENTE"),
        "friendly fire!": ("Fogo amigo!", "URGENTE"),
        "contact at nine o'clock.": ("Contato às 9 horas.", "URGENTE"),
        "contact 8 o'clock!": ("Contato 8 horas!", "URGENTE"),
        "contact seven o'clock!": ("Contato 7 horas!", "URGENTE"),
        "contact six o'clock.": ("Contato 6 horas.", "URGENTE"),
        "contact at five o'clock.": ("Contato às 5 horas.", "URGENTE"),
        "contact four o'clock!": ("Contato 4 horas!", "URGENTE"),
        "contact three o'clock.": ("Contato 3 horas.", "URGENTE"),
        "contact at two o'clock.": ("Contato às 2 horas.", "URGENTE"),
        "contact at 10 o'clock.": ("Contato às 10 horas.", "URGENTE"),
        "contact to the west!": ("Contato ao Oeste!", "URGENTE"),
        "contact southwest!": ("Contato ao Sudoeste!", "URGENTE"),
        "contact southeast!": ("Contato ao Sudeste!", "URGENTE"),
        "contact north west!": ("Contato ao Noroeste!", "URGENTE"),
        "contact to the north east.": ("Contato ao Nordeste.", "URGENTE"),
        "contact to the north!": ("Contato ao Norte!", "URGENTE"),
        "contact to the east.": ("Contato a Leste.", "URGENTE"),
        "friendly fire! friendly fire!": ("Fogo amigo! Fogo amigo!", "URGENTE"),
        "hey, check your fire!": ("Ei, cuidado com os tiros!", "URGENTE"),
        "check your fire!": ("Cuidado com os tiros!", "URGENTE"),
        "the tall blue one on the left!": ("O azul alto à esquerda!", "URGENTE"),
        "contact! nine o'clock!": ("Contato! 9 horas!", "URGENTE"),
        "contact, seven o'clock!": ("Contato, 7 horas!", "URGENTE"),
        "contact! six o'clock!": ("Contato! 6 horas!", "URGENTE"),
        "contact 4 o'clock!": ("Contato 4 horas!", "URGENTE"),
        "contact! three o'clock!": ("Contato! 3 horas!", "URGENTE"),
        "contact two o'clock!": ("Contato 2 horas!", "URGENTE"),
        "contact one o'clock!": ("Contato 1 hora!", "URGENTE"),
        "contact! 12 o'clock!": ("Contato! 12 horas!", "URGENTE"),
        "contact 11 o'clock!": ("Contato 11 horas!", "URGENTE"),
        "contact, 10 o'clock!": ("Contato, 10 horas!", "URGENTE"),
        "coming from the west!": ("Vindo do Oeste!", "URGENTE"),
        "enemy southwest.": ("Inimigo a sudoeste.", "URGENTE"),
        "enemy to the south!": ("Inimigo ao sul!", "URGENTE"),
        "enemies to the northwest!": ("Inimigos ao noroeste!", "URGENTE"),
        "enemies to the northeast.": ("Inimigos ao nordeste.", "URGENTE"),
        "to the north!": ("Ao Norte!", "URGENTE"),
        "enemies in the white building!": ("Inimigos no edifício branco!", "URGENTE"),
        "enemies on the roof of the tall building!": ("Inimigos no teto do edifício alto!", "URGENTE"),
        "contact at 11 o'clock!": ("Contato às 11 horas!", "URGENTE"),
        "contact at 10 o'clock!": ("Contato às 10 horas!", "URGENTE"),
        "contact at 9 o'clock!": ("Contato às 9 horas!", "URGENTE"),
        "contact at 8 o'clock!": ("Contato às 8 horas!", "URGENTE"),
        "contact at 7 o'clock!": ("Contato às 7 horas!", "URGENTE"),
        "contact at 6 o'clock!": ("Contato às 6 horas!", "URGENTE"),
        "contact at 5 o'clock!": ("Contato às 5 horas!", "URGENTE"),
        "contact at 4 o'clock!": ("Contato às 4 horas!", "URGENTE"),
        "contact at 3 o'clock!": ("Contato às 3 horas!", "URGENTE"),
        "contact at 2 o'clock!": ("Contato às 2 horas!", "URGENTE"),
        "contact at 1 o'clock!": ("Contato a 1 hora!", "URGENTE"),
        "contact at 12 o'clock!": ("Contato às 12 horas!", "URGENTE"),
        "the west": ("Ao Oeste", "URGENTE"),
        "i see enemies to the southwest!": ("Vejo inimigos ao sudoeste!", "URGENTE"),
        "they're attacking from the southeast!": ("Estão atacando pelo sudeste!", "URGENTE"),
        "the south!": ("Ao Sul!", "URGENTE"),
        "northwest.": ("Noroeste.", "URGENTE"),
        "i see enemies to the north east!": ("Vejo inimigos ao nordeste!", "URGENTE"),
        "i see them to the north!": ("Estou vendo eles ao norte!", "URGENTE"),
        "soldiers approaching from the east!": ("Soldados se aproximando pelo leste!", "URGENTE"),
        "quit showing off.": ("Pare de se amostrar.", "URGENTE"),
        "that's a new personal best.": ("Esse é um novo recorde pessoal.", "URGENTE"),
        "you can do better than that.": ("Você pode fazer melhor que isso.", "URGENTE"),
        "sprint to the finish!": ("Pique total para a chegada!", "URGENTE"),
        "drop those tangos!": ("Derrube esses alvos!", "URGENTE"),
        "on your go, frost.": ("Quando quiser, Frost.", "URGENTE"),
        "dogs approaching!": ("Cães se aproximando!", "URGENTE"),
        "move, move, move!": ("Mova-se, mova-se, mova-se!", "URGENTE"),
        "no good. run it again.": ("Insuficiente. Faça de novo.", "URGENTE"),
        "nicely done.": ("Belo trabalho.", "URGENTE"),
        "we got stragglers!": ("Temos retardatários!", "URGENTE"),
        "we're gonna need another way out of here!": ("Precisamos de outra saída daqui!", "URGENTE"),
        "all clear!": ("Tudo limpo!", "URGENTE"),
        "i see him!": ("Estou vendo ele!", "URGENTE"),
        "i'm good!": ("Estou bem!", "URGENTE"),
        "we're clear!": ("Tudo limpo!", "URGENTE"),
        "the president is secure!": ("O Presidente está em segurança!", "URGENTE"),
        "we gotta go now!": ("Temos que ir agora!", "URGENTE"),
        "any bright ideas?": ("Alguma ideia brilhante?", "URGENTE"),
        "there they are!": ("Eles estão ali!", "URGENTE"),
        "contact 12 o'clock!": ("Contato às 12 horas!", "URGENTE"),
        "watch the left flank!": ("Cuidado com o flanco esquerdo!", "URGENTE"),
        "i hope this works.": ("Espero que isso funcione.", "URGENTE"),
        "sniper in the tower!": ("Atirador na torre!", "URGENTE"),
        "get down!": ("Se abaixa!", "URGENTE"),
        "stay with me, son!": ("Fica comigo, garoto!", "URGENTE"),
        "makarov knows yuri...": ("O Makarov... conhece o... Yuri...", "URGENTE"),
        "price, we have to move!": ("Price, temos que sair daqui!", "URGENTE"),
        "soap! no! no, no, no!": ("Soap! Não! Não, não, não!", "URGENTE"),
        "perfect.": ("Perfeito!", "URGENTE"),
        "move up.": ("Avançar!", "URGENTE"),
        "do you like the smell of this place? come on, let's go!": ("Gosta do cheiro deste lugar? Vamos, mexam-se!", "URGENTE"),
        "hurry, we don't have much time!": ("Rápido, não temos muito tempo!", "URGENTE"),
        "give me your hand.": ("Me dá a sua mão.", "URGENTE"),
        "what took you so long?": ("Por que demorou tanto?", "URGENTE"),
        "cough cough cough": ("Cough Cough Cough", "URGENTE"),
        "hold your fire!": ("Cessar fogo!", "URGENTE"),
        "friendly forces in the area!": ("Aliados na área!", "URGENTE"),
        "danger close!": ("Perigo próximo!", "URGENTE"),
        "firing 40mm.": ("Disparando 40mm!", "URGENTE"),
        "firing 105mm.": ("Disparando 105mm!", "URGENTE"),
        "target destroyed!": ("Alvo destruído!", "URGENTE"),
        "direct hit!": ("Impacto direto!", "URGENTE"),
        "solid kill.": ("Baixa confirmada!", "URGENTE"),
        "good kill.": ("Boa baixa!", "URGENTE"),
        "good tone, fox 3.": ("Tom bom, Fox 3!", "URGENTE"),
        "circling around to the north.": ("Circulando pelo norte.", "URGENTE"),
        "take out those guys.": ("Elimina aqueles caras!", "URGENTE"),
        "roger.": ("Copiado!", "URGENTE"),
        "fire on that building.": ("Fogo naquele prédio!", "URGENTE"),
        "flares, flares.": ("Flares, Flares!", "URGENTE"),
        "light it up.": ("Abre fogo!", "URGENTE"),
        "good job.": ("Bom trabalho!", "URGENTE"),
        "roger, overlord. we're inbound.": ("Copiado, Overlord. Estamos a caminho.", "URGENTE"),
        "roger that, 24.": ("Copiado, 24.", "URGENTE"),
        "im hit!": ("Fui atingido!", "URGENTE"),
        "man down!": ("Soldado abatido!", "URGENTE"),
        "target neutralized!": ("Alvo neutralizado!", "URGENTE"),
        "target down!": ("Alvo abatido!", "URGENTE"),
        "tango down!": ("Inimigo abatido!", "URGENTE"),
        "area clear!": ("Área limpa!", "URGENTE"),
        "clear!": ("Limpo!", "URGENTE"),
        "grenade!": ("Granada!", "URGENTE"),
        "rpg!": ("RPG à vista!", "URGENTE"),
        "cover me!": ("Me dá cobertura!", "URGENTE"),
        "reloading!": ("Recarregando!", "URGENTE"),
        "watch your fire!": ("Cuidado com o fogo amigo!", "URGENTE"),
        "providing cover fire, move up!": ("Dando fogo de cobertura, avança!", "URGENTE"),
        "adios.": ("Até mais.", "URGENTE"),
        "the balcony's clear!": ("A varanda está limpa!", "URGENTE"),
        "contact!": ("Contato!", "URGENTE"),
        "got you covered!": ("Cobertura garantida!", "URGENTE"),
        "i'm on it.": ("Deixa comigo!", "URGENTE"),
        "raj.": ("Copiado!", "URGENTE"),
        "contact memorial building to the north.": ("Contato no Edifício Memorial ao norte!", "URGENTE"),
        "shooter's in the store below. switch them off.": ("Atirador na loja abaixo. Neutraliza ele!", "URGENTE"),
        "we got company!": ("Temos companhia!", "URGENTE"),
        "moving!": ("EM MOVIMENTO!", "URGENTE"),
        "russian armor incoming!": ("Blindados russos se aproximando!", "URGENTE"),
        "truck, you getting anything on your comms?": ("Truck, pegou alguma coisa no rádio?", "URGENTE"),
        "i like it.": ("Assim que se faz!", "URGENTE"),
        "frost, get in here!": ("Frost, vem pra cá!", "URGENTE"),
        "contact front hostels in the open!": ("Contato à frente! Inimigos a campo aberto!", "URGENTE"),
        "no shit!": ("Sério mesmo?!", "URGENTE"),
        "move move move!": ("VAI! VAI! VAI!", "URGENTE"),
        "we're good!": ("Estamos bem!", "URGENTE"),
        "we got you loud and clear.": ("Copiado alto e claro!", "URGENTE"),
        "good kill, good kill.": ("Alvo destruído, boa baixa!", "URGENTE"),
        "good tone, fox 3, fox 3.": ("Tom bom! Fox 3, Fox 3!", "URGENTE"),
        "check your fire": ("Cuidado com o fogo amigo!", "RAIVA"),
        "jack your fire": ("Cuidado com o fogo amigo!", "RAIVA"),
        "watch your fire": ("Cuidado com o fogo amigo!", "RAIVA"),
        "friendly fire friendly fire": ("Fogo amigo! Fogo amigo!", "RAIVA"),
        "friendly fire": ("Fogo amigo!", "RAIVA"),
        "reloading": ("Recarregando!", "URGENTE"),
        "im reloading": ("Tô recarregando!", "URGENTE"),
        "reloading get cover": ("Recarregando, busca cobertura!", "URGENTE"),
        "cover me": ("Me dá cobertura!", "URGENTE"),
        "cover me im reloading": ("Me dá cobertura, tô recarregando!", "URGENTE"),
        "grenade": ("Granada!", "URGENTE"),
        "frag out": ("Lançando granada!", "URGENTE"),
        "flashbang out": ("Lançando granada de luz!", "URGENTE"),
        "smoke out": ("Lançando fumaça!", "URGENTE"),
        "rpg": ("RPG à vista!", "URGENTE"),
        "sniper": ("Atirador de elite!", "URGENTE"),
        "sniper get down": ("Atirador de elite, se abaixa!", "URGENTE"),
        "man down": ("Soldado abatido!", "DRAMATICO"),
        "im hit": ("Fui atingido!", "URGENTE"),
        "im hit im hit": ("Fui atingido! Fui atingido!", "URGENTE"),
        "taking fire": ("Sob fogo inimigo!", "URGENTE"),
        "under fire": ("Sob fogo inimigo!", "URGENTE"),
        "clear": ("Limpo!", "NORMAL"),
        "area clear": ("Área limpa!", "NORMAL"),
        "all clear": ("Tudo limpo!", "NORMAL"),
        "move move": ("VAI! VAI!", "URGENTE"),
        "move up": ("Avançar!", "URGENTE"),
        "move in": ("Entrando!", "URGENTE"),
        "push forward": ("Avançar!", "URGENTE"),
        "fall back": ("Recuar!", "URGENTE"),
        "hold your ground": ("Mantenham a posição!", "RAIVA"),
        "hold this position": ("Mantenham esta posição!", "RAIVA"),
        "get down": ("Se abaixa!", "URGENTE"),
        "get in cover": ("Busquem cobertura!", "URGENTE"),
        "head down": ("Cabeça baixa!", "URGENTE"),
        "area secure": ("Área limpa!", "NORMAL"),
        "flash out": ("Lançando atordoante!", "URGENTE"),
        "throwing frag": ("Lançando granada!", "URGENTE"),
        "throw in c4": ("Instalando C4!", "URGENTE"),
        "deploying c4": ("Instalando C4!", "URGENTE"),
        "im bleeding out": ("Estou sangrando!", "DRAMATICO"),
        "hurry im bleeding out": ("Rápido, estou sangrando!", "DRAMATICO"),
        "on comms": ("Na frequência!", "NORMAL"),
        "contacting hq": ("Contatando o Comando!", "NORMAL"),
        "target neutralized": ("Alvo neutralizado!", "NORMAL"),
        "target down": ("Alvo abatido!", "URGENTE"),
        "tango down": ("Inimigo abatido!", "URGENTE"),
        "enemy down": ("Inimigo no chão!", "URGENTE"),
        "hes down": ("Ele caiu!", "URGENTE"),
        "mark and drop zone": ("Marcando zona de pouso!", "NORMAL"),
        "russian armor incoming": ("Blindados russos se aproximando!", "URGENTE"),
        "move move move": ("VAI! VAI! VAI!", "URGENTE"),
        "moving": ("EM MOVIMENTO!", "URGENTE"),
        "we got company": ("Temos companhia!", "URGENTE"),
        "got you covered": ("Cobertura garantida!", "NORMAL"),
        "providing cover fire move up": ("Fogo de cobertura, avança!", "URGENTE"),
        "the balconys clear": ("A varanda está limpa!", "NORMAL"),
        "contact": ("Contato!", "URGENTE"),
        "we got you loud and clear": ("Copiado alto e claro!", "NORMAL"),
        "were good": ("Estamos bem!", "NORMAL"),
        "im on it": ("Deixa comigo!", "NORMAL")
    }

    if c_lower in tactical_dict:
        pt_t, emo = tactical_dict[c_lower]
        return pt_t, emo

    return None, None
